server:
  port: 7070
spring:
  cloud:
    nacos:
      discovery:
        ##服务的注册
        server-addr: 127.0.0.1:8848
        ###  nacos 配置中心
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 47.96.105.42
    port: 6369
    password: 123456
  application:
    name: mayikt-member-job
  profiles:
    active: prd
mayikt:
  member:
    job:
      WeChatActivitiePageSize: 2