spring:
  application:
    name: hyxs-weixin
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop?serverTimezone=GMT
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true

swagger:
  base-package: com.hyxs.wechat.impl
  title: SpringCloud2.x构建微服务电商项目-会员服务接口
  description: 该项目“基于SpringCloud2.x构建微服务电商项目”由每特教育|蚂蚁课堂版权所有，未经过允许的情况下，私自分享视频和源码属于违法行为。
  version: 1.1
  terms-of-service-url: www.mayikt.com
  contact:
    name: 97后互联网架构师-余胜军
    email: 644064779@qq.com
    url: www.mayikt.com
  enabled: true

server:
  port: 6060

logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG

wx:
  mp:
    configs:
      - appId: wx3824e5b0329d18d1
        secret: 690678d12e6c42d42ffb90a55997fdd1
        token: hyxs

hyxs:
  weixin:
    registration:
      code:
        message: "老曹最丑"
    default:
      registration:
        code:
          message: "老曹最丑"
    loginTemplateId: DdZ-SE1q80hvsa4dvpUcjRjir1wKENIm6DsfQ0A3bbc